# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-pay-enrichment:
    build:
      target: development
    image: ffc-pay-enrichment-development
    container_name: ffc-pay-enrichment-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      PROCESSING_ACTIVE: true

  ffc-pay-enrichment-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
