version: '3.8'

services:
  ffc-sfi-payment-enrichment:
    build:
      context: .
      target: production
    image: ffc-sfi-payment-enrichment
    container_name: ffc-sfi-payment-enrichment
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-payment-enrichment-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
