version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-payment-enrichment:
    build:
      target: development
    image: ffc-sfi-payment-enrichment-development
    container_name: ffc-sfi-payment-enrichment-development
    ports:
      - "3012:3012"
      - "9241:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
