version: '3.8'

services:
  ffc-pay-enrichment:
    build:
      context: .
      target: production
    image: ffc-pay-enrichment
    depends_on: 
      - ffc-pay-enrichment-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-enrichment-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      PAYMENT_TOPIC_ADDRESS: ${PAYMENT_TOPIC_ADDRESS:-notset}
      PAYMENT_SUBSCRIPTION_ADDRESS: ${PAYMENT_SUBSCRIPTION_ADDRESS:-notset}
      PROCESSING_TOPIC_ADDRESS: ${PROCESSING_TOPIC_ADDRESS:-notset}
      POSTGRES_DB: ffc_sfi_payment_enrichment
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-pay-enrichment-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
  
  ffc-pay-enrichment-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_sfi_payment_enrichment
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
