version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-payment-enrichment:
    build:
      target: development
    image: ffc-sfi-payment-enrichment-development
    ports:
      - "9241:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-sfi-payment-enrichment-postgres:
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
