sonar.javascript.exclusions=**/jest.config.js,**/eslint.config.js,**/__mocks__/**,**/node_modules/**,**/test/**,**/test-output/**,**/app/config/**
sonar.javascript.lcov.reportPaths=test-output/lcov.info
sonar.exclusions=/test/**,**/*.test.js,*snyk_report.html,*snyk_report.css
sonar.issue.ignore.multicriteria=awaitInRetry,awaitInBatchSend,awaitInShutdown
sonar.issue.ignore.multicriteria.awaitInRetry.ruleKey=javascript:S9382
sonar.issue.ignore.multicriteria.awaitInRetry.resourceKey=**/app/messaging/service-bus/retry.js
sonar.issue.ignore.multicriteria.awaitInBatchSend.ruleKey=javascript:S9382
sonar.issue.ignore.multicriteria.awaitInBatchSend.resourceKey=**/app/messaging/service-bus/send-batch-messages.js
sonar.issue.ignore.multicriteria.awaitInShutdown.ruleKey=javascript:S9382
sonar.issue.ignore.multicriteria.awaitInShutdown.resourceKey=**/app/messaging/service-bus/sender-cache.js
