environment: production
environmentCode:
name: ffc-pay-enrichment
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-enrichment

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-enrichment-config-map

containerSecret:
  name: ffc-pay-enrichment-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 16
  cpuThreshold: 80
  memoryThreshold: 80

container:
  requestMemory: 80Mi
  requestCpu: 40m
  limitMemory: 80Mi
  limitCpu: 120m
  messageQueueHost: namespace.servicebus.windows.net
  paymentTopicAddress: ffc-pay-request
  paymentSubscriptionAddress: ffc-pay-enrichment
  processingTopicAddress: ffc-pay-processing
  responseTopicAddress: ffc-pay-request-response
  eventTopicAddress: ffc-pay-event

postgresService:
  postgresDb: ffc_pay_enrichment
  postgresqlHost: ffc-pay-enrichment-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
