environment: production
environmentCode:
name: ffc-pay-enrichment
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-enrichment

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-enrichment-config-map

containerSecret:
  name: ffc-pay-enrichment-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 20
  cpuThreshold: 80
  memoryThreshold: 80

container:
  requestMemory: 150Mi
  requestCpu: 40m
  limitMemory: 200Mi
  limitCpu: 200m
  port: 3009
  messageQueueHost: namespace.servicebus.windows.net
  paymentTopicAddress: ffc-pay-request
  paymentSubscriptionAddress: ffc-pay-enrichment
  processingTopicAddress: ffc-pay-processing
  responseTopicAddress: ffc-pay-request-response
  eventsTopicAddress: ffc-pay-events
  customerTopicAddress: ffc-pay-customer
  customerSubscriptionAddress: ffc-pay-enrichment
  useV2Events: true
  processingActive: true

readinessProbe:
  path: /healthy
  port: 3009
  initialDelaySeconds: 60
  periodSeconds: 120
  failureThreshold: 5
  timeoutSeconds: 30

livenessProbe:
  path: /healthz
  port: 3009
  initialDelaySeconds: 70
  periodSeconds: 120
  failureThreshold: 5
  timeoutSeconds: 30

postgresService:
  postgresDb: ffc_pay_enrichment
  postgresqlHost: ffc-pay-enrichment-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
