---
environment: production
environmentCode: prd
container:
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  processingActive: true
  paymentTopicAddress: ffc-pay-request-prd
  paymentSubscriptionAddress: ffc-pay-enrichment
  processingTopicAddress: ffc-pay-processing-prd
  responseTopicAddress: ffc-pay-request-response-prd
  eventsTopicAddress: ffc-pay-events-prd
  customerTopicAddress: ffc-pay-customer-prd
  customerSubscriptionAddress: ffc-pay-enrichment
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appInsights-connectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-batch-processor
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTION_STRING
