environment: development
name: ffc-sfi-payment-enrichment
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-payment-enrichment

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-sfi-payment-enrichment-config-map

containerSecret:
  name: ffc-sfi-payment-enrichment-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3012

livenessProbe:
  path: /healthz
  port: 3012
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3012
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
