environment: development
name: ffc-sfi-payment-enrichment
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-payment-enrichment

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-sfi-payment-enrichment-config-map

containerSecret:
  name: ffc-sfi-payment-enrichment-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReplicas: 2
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 180Mi
  requestCpu: 120m
  limitMemory: 180Mi
  limitCpu: 120m
  messageQueueHost: namespace.servicebus.windows.net
  paymentTopicAddress: ffc-sfi-payment-request
  paymentSubscriptionAddress: ffc-sfi-payment-request-enrichment
  processingTopicAddress: ffc-sfi-payment-processing

postgresService:
  postgresDb: ffc_sfi_payment_enrichment
  # postgresExternalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible via postgresHost
  postgresExternalName:
  postgresHost: ffc-sfi-payment-enrichment-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
